---
# roles/caddy/handlers/main.yml
- name: reload caddy
  ansible.builtin.systemd:
    name: caddy
    state: reloaded

- name: restart caddy
  ansible.builtin.systemd:
    name: caddy
    state: restarted

- name: daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes
